# Generated by Django 4.1.7 on 2023-02-22 20:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_notes', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('city', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=255)),
                ('project_code', models.CharField(max_length=255)),
                ('summit_username', models.IntegerField(unique=True)),
                ('summit_password', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
