# Generated by Django 4.1.7 on 2023-02-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_notes', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=255)),
                ('project_code', models.CharField(max_length=255)),
                ('summit_username', models.IntegerField(unique=True)),
                ('summit_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
