from django import forms
from .models import SummitData

class SummitForm(forms.ModelForm):
    weekday_choices = (
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday')
    )
    CITY_CHOICES = (
        ('Nashik', 'Nashik'),
        ('Jaulke', 'Jaulke'),
        ('Malsane', 'Malsane'),
        ('Mumbai', 'Mumbai'),
        ('Bangalore', 'Bangalore'),
        ('Pune', 'Pune'),
        ('Satana', 'Satana'),
        ('Abu Dhabi', 'Abu Dhabi'),
        ('Adimal', 'Adimal'),
        ('Africa', 'Africa'),
        ('Ahemdabad', 'Ahemdabad'),
        ('Ahmednagar', 'Ahmednagar'),
        ('Ajmer ', 'Ajmer '),
        ('Ajmer', 'Ajmer'),
        ('Algeria', 'Algeria'),
        ('Alibag', 'Alibag'),
        ('Aligarh', 'Aligarh'),
        ('Alwar', 'Alwar'),
        ('Ambala', 'Ambala'),
        ('Ambarnath', 'Ambarnath'),
        ('Amli', 'Amli'),
        ('Amritsar', 'Amritsar'),
        ('Anand', 'Anand'),
        ('Anantapur', 'Anantapur'),
        ('Atlanta', 'Atlanta'),
        ('Aurangabad', 'Aurangabad'),
        ('Aurangabad', 'Aurangabad'),
        ('Baddi', 'Baddi'),
        ('Baharin', 'Baharin'),
        ('Bandung', 'Bandung'),
        ('Bandung', 'Bandung'),
        ('Bangkok', 'Bangkok'),
        ('Bangladesh', 'Bangladesh'),
        ('Banten', 'Banten'),
        ('BARBARA', 'BARBARA'),
        ('Bareilly', 'Bareilly'),
        ('Baroda', 'Baroda'),
        ('Bathinda', 'Bathinda'),
        ('Belagavi', 'Belagavi'),
        ('Belrose', 'Belrose'),
        ('Bharuch', 'Bharuch'),
        ('Bhavnagar', 'Bhavnagar'),
        ('Bhivandi', 'Bhivandi'),
        ('Bhopal', 'Bhopal'),
        ('Bhubhaneshwar', 'Bhubhaneshwar'),
        ('Bijapur', 'Bijapur'),
        ('Bikaner', 'Bikaner'),
        ('Bilaspur', 'Bilaspur'),
        ('Brazil', 'Brazil'),
        ('Cairo', 'Cairo'),
        ('Cato Ridge', 'Cato Ridge'),
        ('Chamarajanagar', 'Chamarajanagar'),
        ('Chandigarh', 'Chandigarh'),
        ('Chandwad', 'Chandwad'),
        ('Changzhou', 'Changzhou'),
        ('Channo', 'Channo'),
        ('Charlotte', 'Charlotte'),
        ('Chennai', 'Chennai'),
        ('Cherlapally', 'Cherlapally'),
        ('Cheyyar', 'Cheyyar'),
        ('Chheharta', 'Chheharta'),
        ('Chikmagalur', 'Chikmagalur'),
        ('Chilaw', 'Chilaw'),
        ('Chiplun', 'Chiplun'),
        ('Chittagong', 'Chittagong'),
        ('Chittoor', 'Chittoor'),
        ('Chuzhou', 'Chuzhou'),
        ('Cochin', 'Cochin'),
        ('Coevorden', 'Coevorden'),
        ('Coimbatore', 'Coimbatore'),
        ('colombo', 'colombo'),
        ('Cork', 'Cork'),
        ('Dabhel', 'Dabhel'),
        ('Dalian', 'Dalian'),
        ('Daman', 'Daman'),
        ('Dapada', 'Dapada'),
        ('Darrang', 'Darrang'),
        ('Dehradun', 'Dehradun'),
        ('Delhi', 'Delhi'),
        ('Dewas', 'Dewas'),
        ('Dhaka', 'Dhaka'),
        ('Dhar', 'Dhar'),
        ('Dharwad', 'Dharwad'),
        ('Dholka', 'Dholka'),
        ('Dhule', 'Dhule'),
        ('Diyodar', 'Diyodar'),
        ('Dombivali', 'Dombivali'),
        ('Dubai', 'Dubai'),
        ('Dublin', 'Dublin'),
        ('Durrainalur', 'Durrainalur'),
        ('Dusseldorf', 'Dusseldorf'),
        ('Ede', 'Ede'),
        ('Egypt', 'Egypt'),
        ('Ernakulam', 'Ernakulam'),
        ('Ernakulam', 'Ernakulam'),
        ('Etah', 'Etah'),
        ('Etawah', 'Etawah'),
        ('Etha', 'Etha'),
        ('Faridabad', 'Faridabad'),
        ('Farrukhnagar', 'Farrukhnagar'),
        ('Farukhnagar', 'Farukhnagar'),
        ('Gandhidham', 'Gandhidham'),
        ('Gandhinagar ', 'Gandhinagar '),
        ('Ganjingzi', 'Ganjingzi'),
        ('Gautam Budha Nagar', 'Gautam Budha Nagar'),
        ('Germany', 'Germany'),
        ('Gewerbepark Urfahr', 'Gewerbepark Urfahr'),
        ('Ghaziabad', 'Ghaziabad'),
        ('Goa', 'Goa'),
        ('Greenwood', 'Greenwood'),
        ('Grove', 'Grove'),
        ('Guangzhou', 'Guangzhou'),
        ('Gurgaon', 'Gurgaon'),
        ('Guwahati', 'Guwahati'),
        ('Gwalior', 'Gwalior'),
        ('Haldia', 'Haldia'),
        ('Hamirpur', 'Hamirpur'),
        ('Harderwijk', 'Harderwijk'),
        ('Haridwar', 'Haridwar'),
        ('Hetauda', 'Hetauda'),
        ('Hetauda', 'Hetauda'),
        ('Hilliard', 'Hilliard'),
        ('Hilliard', 'Hilliard'),
        ('Hilliard', 'Hilliard'),
        ('Himatnagar', 'Himatnagar'),
        ('Hooghly', 'Hooghly'),
        ('Hoskote Taluk', 'Hoskote Taluk'),
        ('Hosur', 'Hosur'),
        ('Howrah', 'Howrah'),
        ('Huanggang', 'Huanggang'),
        ('Hubali', 'Hubali'),
        ('Huzhou', 'Huzhou'),
        ('Huzhou', 'Huzhou'),
        ('Huzhou', 'Huzhou'),
        ('Huzhou', 'Huzhou'),
        ('Huzhou', 'Huzhou'),
        ('Huzhou', 'Huzhou'),
        ('Hyderabad', 'Hyderabad'),
        ('Hyderabad', 'Hyderabad'),
        ('Icchapore', 'Icchapore'),
        ('Igatpuri', 'Igatpuri'),
        ('Ikeja', 'Ikeja'),
        ('Illinois', 'Illinois'),
        ('Indore', 'Indore'),
        ('Jaipur ', 'Jaipur '),
        ('Jaipur', 'Jaipur'),
        ('Jaipur', 'Jaipur'),
        ('Jakarta', 'Jakarta'),
        ('Jammu', 'Jammu'),
        ('Jeddah', 'Jeddah'),
        ('JEONJU', 'JEONJU'),
        ('Jhagadia GIDC', 'Jhagadia GIDC'),
        ('Jiangsu', 'Jiangsu'),
        ('Kakarbhitta', 'Kakarbhitta'),
        ('Kanakapura', 'Kanakapura'),
        ('Kanpur Deha', 'Kanpur Deha'),
        ('Kapurthala', 'Kapurthala'),
        ('Karachi', 'Karachi'),
        ('Kasaba Hobli', 'Kasaba Hobli'),
        ('Kasai City', 'Kasai City'),
        ('Katha', 'Katha'),
        ('Kathmandu', 'Kathmandu'),
        ('Khalapur', 'Khalapur'),
        ('Khamgaon ', 'Khamgaon '),
        ('Kheda', 'Kheda'),
        ('Khobar', 'Khobar'),
        ('Khorda', 'Khorda'),
        ('Kihonda', 'Kihonda'),
        ('Kluang', 'Kluang'),
        ('Kolhapur', 'Kolhapur'),
        ('Kolkata', 'Kolkata'),
        ('Kopargaon', 'Kopargaon'),
        ('Koramangala', 'Koramangala'),
        ('Kowloon', 'Kowloon'),
        ('Kowloon', 'Kowloon'),
        ('Kowloon', 'Kowloon'),
        ('Kundane', 'Kundane'),
        ('Kutch', 'Kutch'),
        ('Kutch', 'Kutch'),
        ('Lagos', 'Lagos'),
        ('Lahore', 'Lahore'),
        ('Leeuwarden', 'Leeuwarden'),
        ('Lixia', 'Lixia'),
        ('Lonavala', 'Lonavala'),
        ('Lucknow', 'Lucknow'),
        ('Ludhiana', 'Ludhiana'),
        ('Madurai', 'Madurai'),
        ('Malanpur', 'Malanpur'),
        ('Malanpur', 'Malanpur'),
        ('Malegaon', 'Malegaon'),
        ('Malur', 'Malur'),
        ('Manchar', 'Manchar'),
        ('Mandaluyong', 'Mandaluyong'),
        ('Mandideep', 'Mandideep'),
        ('Manglore', 'Manglore'),
        ('Manmad', 'Manmad'),
        ('Mathura', 'Mathura'),
        ('Medchal ', 'Medchal '),
        ('Medchal–Malkajgiri', 'Medchal–Malkajgiri'),
        ('Mehsana', 'Mehsana'),
        ('Mewat', 'Mewat'),
        ('Mexico', 'Mexico'),
        ('Mirigama ', 'Mirigama '),
        ('Mogar', 'Mogar'),
        ('Mogar', 'Mogar'),
        ('Muscat', 'Muscat'),
        ('Muscat', 'Muscat'),
        ('Muzaffarpur', 'Muzaffarpur'),
        ('Mysore', 'Mysore'),
        ('Nadiad', 'Nadiad'),
        ('Nagaon', 'Nagaon'),
        ('Nagpur', 'Nagpur'),
        ('Nanjing', 'Nanjing'),
        ('Narayangaon', 'Narayangaon'),
        ('Navi Mumbai', 'Navi Mumbai'),
        ('Nellore', 'Nellore'),
        ('New Delhi', 'New Delhi'),
        ('New York City', 'New York City'),
        ('NG Geldrop', 'NG Geldrop'),
        ('Niphad', 'Niphad'),
        ('NOIDA', 'NOIDA'),
        ('Ota', 'Ota'),
        ('Palanpur', 'Palanpur'),
        ('Palghar', 'Palghar'),
        ('Panchgani', 'Panchgani'),
        ('Panipat', 'Panipat'),
        ('Pantnagar', 'Pantnagar'),
        ('Patiyala', 'Patiyala'),
        ('Patna', 'Patna'),
        ('Pattaya', 'Pattaya'),
        ('Patuadi', 'Patuadi'),
        ('Pimpalgaon', 'Pimpalgaon'),
        ('Pithampur', 'Pithampur'),
        ('Poland', 'Poland'),
        ('Ponda', 'Ponda'),
        ('Ponda4', 'Ponda4'),
        ('Pondicherry', 'Pondicherry'),
        ('Raigad', 'Raigad'),
        ('Rail Majra', 'Rail Majra'),
        ('Raipur', 'Raipur'),
        ('Raisen', 'Raisen'),
        ('Rajkot', 'Rajkot'),
        ('Rajkot', 'Rajkot'),
        ('Rajnandgaon', 'Rajnandgaon'),
        ('Ramhari Mangaldai', 'Ramhari Mangaldai'),
        ('Ranchi', 'Ranchi'),
        ('Rangsit', 'Rangsit'),
        ('Ranipur', 'Ranipur'),
        ('Ranjangaon', 'Ranjangaon'),
        ('Rayong', 'Rayong'),
        ('Rewari', 'Rewari'),
        ('Riyadh', 'Riyadh'),
        ('Ropar', 'Ropar'),
        ('Rudrapur', 'Rudrapur'),
        ('Sadashivpeth', 'Sadashivpeth'),
        ('Salcete', 'Salcete'),
        ('Salem', 'Salem'),
        ('SALMAN INDUSTRIAL CITY', 'SALMAN INDUSTRIAL CITY'),
        ('Sanand', 'Sanand'),
        ('Sangamner', 'Sangamner'),
        ('Sanya Onoda', 'Sanya Onoda'),
        ('Saransk', 'Saransk'),
        ('Satara', 'Satara'),
        ('Secunderabad', 'Secunderabad'),
        ('Shamshabad', 'Shamshabad'),
        ('Shanghai', 'Shanghai'),
        ('Sharjah', 'Sharjah'),
        ('Shenzhen', 'Shenzhen'),
        ('Shenzhen', 'Shenzhen'),
        ('Shenzhen ', 'Shenzhen '),
        ('Silvassa', 'Silvassa'),
        ('Singapore', 'Singapore'),
        ('Sinnar', 'Sinnar'),
        ('Sitarganj', 'Sitarganj'),
        ('Sogras', 'Sogras'),
        ('Sohar', 'Sohar'),
        ('Sokya', 'Sokya'),
        ('Solan', 'Solan'),
        ('Sonipat ', 'Sonipat '),
        ('Sricity', 'Sricity'),
        ('Sultanate of Oman', 'Sultanate of Oman'),
        ('Sumerpur', 'Sumerpur'),
        ('Sumerpur', 'Sumerpur'),
        ('Surat', 'Surat'),
        ('Surendranagar', 'Surendranagar'),
        ('Suzhou', 'Suzhou'),
        ('Tada, Nellore', 'Tada, Nellore'),
        ('Talaja', 'Talaja'),
        ('Talegaon', 'Talegaon'),
        ('Taloja', 'Taloja'),
        ('Tambaram', 'Tambaram'),
        ('Taoyuan City', 'Taoyuan City'),
        ('Tehran', 'Tehran'),
        ('Tehsil Badli', 'Tehsil Badli'),
        ('Telgate (BG)', 'Telgate (BG)'),
        ('Test', 'Test'),
        ('test', 'test'),
        ('Texas 78731', 'Texas 78731'),
        ('Thane', 'Thane'),
        ('Thiruvallur', 'Thiruvallur'),
        ('Tiexi', 'Tiexi'),
        ('Udaipur', 'Udaipur'),
        ('Udham Singh Nagar', 'Udham Singh Nagar'),
        ('Ulft', 'Ulft'),
        ('Uluberia', 'Uluberia'),
        ('Umrangso', 'Umrangso'),
        ('Vadamangalam', 'Vadamangalam'),
        ('Vadodara', 'Vadodara'),
        ('Vanha Maantie', 'Vanha Maantie'),
        ('Vapi', 'Vapi'),
        ('Varanasi', 'Varanasi'),
        ('Vemanapally', 'Vemanapally'),
        ('Virar', 'Virar'),
        ('Visakhapatnam', 'Visakhapatnam'),
        ('Wiesengasse', 'Wiesengasse'),
        ('Września', 'Września'),
        ('Zhejiang', 'Zhejiang')

    )

    medium_Coices = (('Solo', 'Solo' ),
        ('Email', 'Email'))
    weekday = forms.MultipleChoiceField(choices=weekday_choices, widget=forms.CheckboxSelectMultiple)
    city = forms.ChoiceField(choices=CITY_CHOICES)
    medium = forms.ChoiceField(choices=medium_Coices)
    class Meta:
        model = SummitData
        fields = ['task_name', 'task_notes', 'city', 'medium', 
        'project_code', 'summit_username', 'summit_password', 'weekday']
        widgets = {
            'summit_username': forms.TextInput(attrs={'type': 'number'}),
        }

    def get_initial(self):
        initial = super().get_initial()
        if self.instance:
            initial['weekday'] = self.instance.weekdays.split(',')
        return initial